//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""f7d3f15d-fcea-4e54-b67f-90cf3b01f281"",
            ""actions"": [
                {
                    ""name"": ""Player1-Color1"",
                    ""type"": ""Button"",
                    ""id"": ""eeeb2be4-55b4-429a-aa77-7c43033bc57f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1-Color2"",
                    ""type"": ""Button"",
                    ""id"": ""7f6dc75c-bc1e-463e-b580-351e6d3f7904"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1-Color3"",
                    ""type"": ""Button"",
                    ""id"": ""3bba56b1-0ab6-481a-a126-868937b5fa5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2-Color1"",
                    ""type"": ""Button"",
                    ""id"": ""e87a3140-93bf-4a92-a461-576f4f8b245e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2-Color2"",
                    ""type"": ""Button"",
                    ""id"": ""98176a3c-57b1-4b37-9562-579366d0ca57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2-Color3"",
                    ""type"": ""Button"",
                    ""id"": ""db417618-0e52-4541-a80b-9cfd5465e2e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3-Color1"",
                    ""type"": ""Button"",
                    ""id"": ""03f9c613-288b-46f3-8516-5b84b4a9b542"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3-Color2"",
                    ""type"": ""Button"",
                    ""id"": ""2036e715-c98a-49a3-ae04-6d45b845d25c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3-Color3"",
                    ""type"": ""Button"",
                    ""id"": ""ca292c7d-afe3-461d-92c5-774a6af306f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4-Color1"",
                    ""type"": ""Button"",
                    ""id"": ""ea8840ec-f16d-4f25-9952-a987910713cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4-Color2"",
                    ""type"": ""Button"",
                    ""id"": ""ec807063-643e-4d2f-9fe0-f1cfff665e9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4-Color3"",
                    ""type"": ""Button"",
                    ""id"": ""4d28a25c-074a-4076-ad1c-df53d03cf1e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""18beecee-7148-4e31-9353-138cda51a9ce"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1-Color1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5dae872-4c4c-4f81-bfc5-bfd73c9dfd84"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1-Color2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""496a02af-8663-489a-aad3-7197e1ef4979"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1-Color3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ea9229b-4911-4745-afcd-5db1a742f950"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2-Color1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""611f1a0b-6370-455d-b730-d2f25dd621b1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2-Color2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""315f910d-7b8f-4912-ad68-18079af17a09"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2-Color3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5edc811-1560-4b84-8c63-cadd17e3bd06"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player3-Color1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""447c40ec-31dc-4978-8220-6f381312f364"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player3-Color2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17d308b1-630e-4d02-ad73-30ab34674127"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player3-Color3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""884db664-539d-47f7-b437-783d18ca948e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player4-Color1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51b9a64b-4a2b-4693-a5cd-86270dfbe0fd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player4-Color2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edb68095-21ac-483c-988c-874435299fb3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player4-Color3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Clavier"",
            ""bindingGroup"": ""Clavier"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""ArcadBorn"",
            ""bindingGroup"": ""ArcadBorn"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Player1Color1 = m_Game.FindAction("Player1-Color1", throwIfNotFound: true);
        m_Game_Player1Color2 = m_Game.FindAction("Player1-Color2", throwIfNotFound: true);
        m_Game_Player1Color3 = m_Game.FindAction("Player1-Color3", throwIfNotFound: true);
        m_Game_Player2Color1 = m_Game.FindAction("Player2-Color1", throwIfNotFound: true);
        m_Game_Player2Color2 = m_Game.FindAction("Player2-Color2", throwIfNotFound: true);
        m_Game_Player2Color3 = m_Game.FindAction("Player2-Color3", throwIfNotFound: true);
        m_Game_Player3Color1 = m_Game.FindAction("Player3-Color1", throwIfNotFound: true);
        m_Game_Player3Color2 = m_Game.FindAction("Player3-Color2", throwIfNotFound: true);
        m_Game_Player3Color3 = m_Game.FindAction("Player3-Color3", throwIfNotFound: true);
        m_Game_Player4Color1 = m_Game.FindAction("Player4-Color1", throwIfNotFound: true);
        m_Game_Player4Color2 = m_Game.FindAction("Player4-Color2", throwIfNotFound: true);
        m_Game_Player4Color3 = m_Game.FindAction("Player4-Color3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_Player1Color1;
    private readonly InputAction m_Game_Player1Color2;
    private readonly InputAction m_Game_Player1Color3;
    private readonly InputAction m_Game_Player2Color1;
    private readonly InputAction m_Game_Player2Color2;
    private readonly InputAction m_Game_Player2Color3;
    private readonly InputAction m_Game_Player3Color1;
    private readonly InputAction m_Game_Player3Color2;
    private readonly InputAction m_Game_Player3Color3;
    private readonly InputAction m_Game_Player4Color1;
    private readonly InputAction m_Game_Player4Color2;
    private readonly InputAction m_Game_Player4Color3;
    public struct GameActions
    {
        private @InputActions m_Wrapper;
        public GameActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Player1Color1 => m_Wrapper.m_Game_Player1Color1;
        public InputAction @Player1Color2 => m_Wrapper.m_Game_Player1Color2;
        public InputAction @Player1Color3 => m_Wrapper.m_Game_Player1Color3;
        public InputAction @Player2Color1 => m_Wrapper.m_Game_Player2Color1;
        public InputAction @Player2Color2 => m_Wrapper.m_Game_Player2Color2;
        public InputAction @Player2Color3 => m_Wrapper.m_Game_Player2Color3;
        public InputAction @Player3Color1 => m_Wrapper.m_Game_Player3Color1;
        public InputAction @Player3Color2 => m_Wrapper.m_Game_Player3Color2;
        public InputAction @Player3Color3 => m_Wrapper.m_Game_Player3Color3;
        public InputAction @Player4Color1 => m_Wrapper.m_Game_Player4Color1;
        public InputAction @Player4Color2 => m_Wrapper.m_Game_Player4Color2;
        public InputAction @Player4Color3 => m_Wrapper.m_Game_Player4Color3;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @Player1Color1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color1;
                @Player1Color1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color1;
                @Player1Color1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color1;
                @Player1Color2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color2;
                @Player1Color2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color2;
                @Player1Color2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color2;
                @Player1Color3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color3;
                @Player1Color3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color3;
                @Player1Color3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer1Color3;
                @Player2Color1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color1;
                @Player2Color1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color1;
                @Player2Color1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color1;
                @Player2Color2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color2;
                @Player2Color2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color2;
                @Player2Color2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color2;
                @Player2Color3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color3;
                @Player2Color3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color3;
                @Player2Color3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer2Color3;
                @Player3Color1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color1;
                @Player3Color1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color1;
                @Player3Color1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color1;
                @Player3Color2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color2;
                @Player3Color2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color2;
                @Player3Color2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color2;
                @Player3Color3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color3;
                @Player3Color3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color3;
                @Player3Color3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer3Color3;
                @Player4Color1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color1;
                @Player4Color1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color1;
                @Player4Color1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color1;
                @Player4Color2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color2;
                @Player4Color2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color2;
                @Player4Color2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color2;
                @Player4Color3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color3;
                @Player4Color3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color3;
                @Player4Color3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPlayer4Color3;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Player1Color1.started += instance.OnPlayer1Color1;
                @Player1Color1.performed += instance.OnPlayer1Color1;
                @Player1Color1.canceled += instance.OnPlayer1Color1;
                @Player1Color2.started += instance.OnPlayer1Color2;
                @Player1Color2.performed += instance.OnPlayer1Color2;
                @Player1Color2.canceled += instance.OnPlayer1Color2;
                @Player1Color3.started += instance.OnPlayer1Color3;
                @Player1Color3.performed += instance.OnPlayer1Color3;
                @Player1Color3.canceled += instance.OnPlayer1Color3;
                @Player2Color1.started += instance.OnPlayer2Color1;
                @Player2Color1.performed += instance.OnPlayer2Color1;
                @Player2Color1.canceled += instance.OnPlayer2Color1;
                @Player2Color2.started += instance.OnPlayer2Color2;
                @Player2Color2.performed += instance.OnPlayer2Color2;
                @Player2Color2.canceled += instance.OnPlayer2Color2;
                @Player2Color3.started += instance.OnPlayer2Color3;
                @Player2Color3.performed += instance.OnPlayer2Color3;
                @Player2Color3.canceled += instance.OnPlayer2Color3;
                @Player3Color1.started += instance.OnPlayer3Color1;
                @Player3Color1.performed += instance.OnPlayer3Color1;
                @Player3Color1.canceled += instance.OnPlayer3Color1;
                @Player3Color2.started += instance.OnPlayer3Color2;
                @Player3Color2.performed += instance.OnPlayer3Color2;
                @Player3Color2.canceled += instance.OnPlayer3Color2;
                @Player3Color3.started += instance.OnPlayer3Color3;
                @Player3Color3.performed += instance.OnPlayer3Color3;
                @Player3Color3.canceled += instance.OnPlayer3Color3;
                @Player4Color1.started += instance.OnPlayer4Color1;
                @Player4Color1.performed += instance.OnPlayer4Color1;
                @Player4Color1.canceled += instance.OnPlayer4Color1;
                @Player4Color2.started += instance.OnPlayer4Color2;
                @Player4Color2.performed += instance.OnPlayer4Color2;
                @Player4Color2.canceled += instance.OnPlayer4Color2;
                @Player4Color3.started += instance.OnPlayer4Color3;
                @Player4Color3.performed += instance.OnPlayer4Color3;
                @Player4Color3.canceled += instance.OnPlayer4Color3;
            }
        }
    }
    public GameActions @Game => new GameActions(this);
    private int m_ClavierSchemeIndex = -1;
    public InputControlScheme ClavierScheme
    {
        get
        {
            if (m_ClavierSchemeIndex == -1) m_ClavierSchemeIndex = asset.FindControlSchemeIndex("Clavier");
            return asset.controlSchemes[m_ClavierSchemeIndex];
        }
    }
    private int m_ArcadBornSchemeIndex = -1;
    public InputControlScheme ArcadBornScheme
    {
        get
        {
            if (m_ArcadBornSchemeIndex == -1) m_ArcadBornSchemeIndex = asset.FindControlSchemeIndex("ArcadBorn");
            return asset.controlSchemes[m_ArcadBornSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnPlayer1Color1(InputAction.CallbackContext context);
        void OnPlayer1Color2(InputAction.CallbackContext context);
        void OnPlayer1Color3(InputAction.CallbackContext context);
        void OnPlayer2Color1(InputAction.CallbackContext context);
        void OnPlayer2Color2(InputAction.CallbackContext context);
        void OnPlayer2Color3(InputAction.CallbackContext context);
        void OnPlayer3Color1(InputAction.CallbackContext context);
        void OnPlayer3Color2(InputAction.CallbackContext context);
        void OnPlayer3Color3(InputAction.CallbackContext context);
        void OnPlayer4Color1(InputAction.CallbackContext context);
        void OnPlayer4Color2(InputAction.CallbackContext context);
        void OnPlayer4Color3(InputAction.CallbackContext context);
    }
}
